server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: peer1
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka/
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: kfcoding-ereka
logging:
  level:
    root: info
    com.cuiyun: debug

