server:
  port: 8761

eureka:
  client:
    register-with-eureka: false #是否将自己注册到Eureka Server
    fetch-registry: false #是否从Eureka Server获取注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: kfcoding-ereka
