server:
  port: 8762
eureka:
  server:
      enable-self-preservation: false
  instance:
    hostname: peer2
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: kfcoding-ereka

logging:
  level:
    root: info
    com.cuiyun: debug