server:
  port: 9411
spring:
  application:
    name: kfcoding-zipkin

eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
